apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
  - image: juantenagimeno/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.js'
          dest: .
  - image: juantenagimeno/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: juantenagimeno/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: juantenagimeno/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: juantenagimeno/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: juantenagimeno/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .